In [3]:
#  Task1 
# This is a Python comment. It is used to explain the code and is ignored during execution.
"""
In Jupyter Notebooks, markdown cells are used to format text, include
headings, images, and more.
"""

'\nIn Jupyter Notebooks, markdown cells are used to format text, include\nheadings, images, and more.\n'

# This is a markdown cell in Jupyter

# Task 2: Create Array 1D

In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [13]:
#Create a 1D NumPy array with values ranging from 1 to 10.
import numpy as np
arr_1d=np.arange(1,11)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
#Create a 2D array of zeros with the shape (3, 4).
arr_2d=np.zeros((3,4));
arr_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
#create 3x3 array of ones
arr_ones=np.ones((3,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Task 3: Use of `arange()` and `reshape()`

In [32]:
arr_arange=np.arange((20))
arr_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
arr_reshape=arr_arange.reshape(4,5)
arr_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Task 4: Array Shape

In [39]:
# Print the shape of both arrays created in Task 3 (before and after reshaping).
print('Shape before reshaping:', arr_arange.shape)
print('Shape after reshaping:', arr_reshape.shape)

Shape before reshaping: (20,)
Shape after reshaping: (4, 5)


In [41]:
## Verify the number of elements before and after reshaping are consistent.
print('Number of elements before reshaping:', arr_arange.size)
print('Number of elements after reshaping:', arr_reshape.size)

Number of elements before reshaping: 20
Number of elements after reshaping: 20


# Task 5: indexing

In [37]:
arr_random=np.random.randint(1,101,10)
arr_random

array([44, 46, 34, 13, 74, 56, 25, 91, 75, 69])

### Extracting

In [49]:
# first element
print("the the first element is ", arr_random[0])
#the last element
print("the the last element is ", arr_random[-1])
#Elements from index 2 to 5:
print("Elements from index 2 to 5:", arr_random[2:6])
# Every second element of the array.
print('Every second element:', arr_random[::2])

the the first element is  44
the the last element is  69
Elements from index 2 to 5: [34 13 74 56]
Every second element: [44 34 74 25 75]


# Task 6: Advanced Indexing

### Create a 2D NumPy array with random integers between 1 and 10 with a shape of (4,4).

arr_2d=np.random.randint(1,11,(4,4))
arr_2d

### Extracting

#The element at row 1, column 2
print('Element at row 1, column 2:', arr_2d[1, 2])
#All elements from the 2nd row
print('All elements from the 2nd row:', arr_2d[1, :])
#All elements from the 3rd column.
print('All elements from the 3rd column:', arr_2d[:, 2])

# Task 7: Reshaping & Indexing Combination

### Use the `arange()` function to create an array of 25 elements and reshape it into a 5x5
array.

In [61]:
arr_large=np.arange(25).reshape(5,5)
arr_large

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Exctracting

In [65]:
#The element at row 3, column 4
print('Element at row 3, column 4:', arr_large[3, 4])
#The last row
print('Last row:', arr_large[-1])
#- A subarray containing the first two rows and columns.
print('Subarray (first two rows and columns):\n', arr_large[:2, :2])

Element at row 3, column 4: 19
Last row: [20 21 22 23 24]
Subarray (first two rows and columns):
 [[0 1]
 [5 6]]


In [3]:
import numpy as np
List =np.arange(1,21).reshape(4,5)
List

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
Mean=np.mean(List)
Mean

10.5

In [9]:
Sum=np.sum(List)
Sum

210

In [11]:
Median=np.median(List)
Median

10.5

In [13]:
Mode=np.mode(List)
Mode

AttributeError: module 'numpy' has no attribute 'mode'

# range , varience, std 

In [27]:
import numpy as np;
from scipy import stats;
data=np.array([8,2,5,7,3,2,9,10,18,20])
print(data)
#range
Range=np.ptp(data)
print("The range of data: ",Range)
#Varience
var_vl=np.var(data)
print("varience of data: ",var_vl)

std_vl=np.std(data)

print("The std of data: ",std_vl)

#mode value
mode_value=stats.mode(data)
print("The count of data: ",mode_value)

# count of data
counting=np.count_nonzero(data)
print("Counting data",counting)

[ 8  2  5  7  3  2  9 10 18 20]
The range of data:  18
varience of data:  35.440000000000005
The std of data:  5.953150426454887
The count of data:  ModeResult(mode=2, count=2)
Counting data 10


## Quirtiles

In [42]:
# Display the first quartile of data
#percentile ==> quartile
q1=np.percentile(data,25)
q1
# q2
q2=np.percentile(data,50)
#q3
q3=np.percentile(data,75)
print("The first quartile:",{q1}, "\n the second quartile: ",{q2},"\n the second quartile: ",{q3})
iqr=q3-q1
print("IQR is: ", iqr)

# lower outlier
lower=q1-1.5*iqr
print("lower bound is: " ,lower)
upper=q3+1.5*iqr
print("upper bound is: ", upper)


The first quartile: {3.5} 
 the second quartile:  {7.5} 
 the second quartile:  {9.75}
IQR is:  6.25
lower bound is:  -5.875
upper bound is:  19.125


In [44]:
# detect the outlier of our data
outlier=data[(data<lower)|(data>upper)]
print("these are the outliers of our data", outlier)

these are the outliers of our data [20]


# Arithmatic operation

In [51]:
# 2d
data2=np.array([[23,1,5,7],[8,5,32,8]])
data2

array([[23,  1,  5,  7],
       [ 8,  5, 32,  8]])

In [71]:
print(data2[1:3:2])

[[ 8  5 32  8]]


In [53]:
# add the data 5
add=data2 +5
print("after addition:\n",add)
#substraction
sub=data2 -5
print("after sub:\n",sub)
#multiply
multi=data2 *5
print("after multiply:\n",multi)
#divission
div=data2 /5
print("after division:\n",div)




after addition:
 [[28  6 10 12]
 [13 10 37 13]]
after sub:
 [[18 -4  0  2]
 [ 3  0 27  3]]
after multiply:
 [[115   5  25  35]
 [ 40  25 160  40]]
after division:
 [[4.6 0.2 1.  1.4]
 [1.6 1.  6.4 1.6]]


In [61]:
print(data2[1])

[ 8  5 32  8]


In [75]:
data3=np.array([5,1,3,4,9,99,23,33,22])

print(data3[1:5])
print(data3[4:])
print(data3[:])

[1 3 4 9]
[ 9 99 23 33 22]
[ 5  1  3  4  9 99 23 33 22]
